# Generated by Django 4.1.7 on 2023-10-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='characteristic_quantities',
            field=models.ManyToManyField(blank=True, null=True, to='product.characteristicquantity'),
        ),
    ]
