# Generated by Django 4.1.7 on 2024-02-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cartitem_user_profile_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='handle',
        ),
    ]
