# Generated by Django 4.1.7 on 2023-11-28 21:30

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=apps.product.models.characteristic_image_path),
        ),
    ]
