# Generated by Django 4.1.7 on 2023-10-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_cartitem_characteristic_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='characteristic_quantities',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='characteristic_quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.characteristicquantity'),
        ),
    ]
