# Generated by Django 4.1.7 on 2023-12-09 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0003_alter_characteristicimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='user.userprofile'),
            preserve_default=False,
        ),
    ]
