# Generated by Django 4.1.7 on 2023-10-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cartitem_characteristic_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
