# Generated by Django 4.1.7 on 2023-12-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cartitem_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
