# Generated by Django 4.1.7 on 2023-10-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
