# Generated by Django 4.1.7 on 2023-12-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='characteristic_quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='characteristics',
            field=models.ManyToManyField(through='product.CharacteristicQuantity', to='product.productcharacteristic'),
        ),
    ]
