# Generated by Django 4.1.7 on 2023-10-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
