# Generated by Django 4.1.7 on 2023-12-18 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_cartitem_characteristic_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='characteristics',
        ),
        migrations.AlterField(
            model_name='characteristicquantity',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_quantities', to='product.cartitem'),
        ),
    ]
