# Generated by Django 4.1.7 on 2023-12-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_cartitem_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='categories',
            field=models.ManyToManyField(to='product.category'),
        ),
    ]
