# Generated by Django 4.1.7 on 2023-11-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productcharacteristic_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='characteristics', to='product.characteristicimage'),
        ),
    ]
