# Generated by Django 4.1.7 on 2023-11-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_category_parent_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_characteristics', to='product.characteristicimage'),
        ),
    ]
