# Generated by Django 4.1.7 on 2023-11-15 13:23

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to=apps.user.models.review_image_path),
        ),
    ]
