# Generated by Django 4.1.7 on 2023-10-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='status_changed',
            field=models.BooleanField(default=False),
        ),
    ]
