# Generated by Django 4.1.7 on 2023-11-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_sellerapplication_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='premium_tariff',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
