# Generated by Django 4.1.7 on 2023-11-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_premium_tariff_alter_seller_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='premium_tariff',
            field=models.CharField(choices=[(1, 'Basic'), (2, 'Standard'), (3, 'Premium')], default='basic', max_length=10),
        ),
    ]
