# Generated by Django 4.1.7 on 2023-11-15 13:23

import apps.seller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_seller_premium_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='store_name',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[apps.seller.models.validate_seller_name]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='store_name',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[apps.seller.models.validate_seller_name]),
        ),
    ]
