# Generated by Django 4.1.7 on 2023-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_seller_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='avatarka',
            field=models.ImageField(upload_to='sellers_avatarka/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='background',
            field=models.ImageField(upload_to='sellers_background/'),
            preserve_default=False,
        ),
    ]
