# Generated by Django 4.1.7 on 2023-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_seller_avatarka_seller_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='avatarka',
            field=models.ImageField(blank=True, null=True, upload_to='sellers_avatarka/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='sellers_background/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='premium_tariff',
            field=models.IntegerField(choices=[(1, 'Basic'), (2, 'Standard'), (3, 'Premium')], default=1),
        ),
    ]
